/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layouts/AppLayout.vue')['default']
    AppMain: typeof import('./components/layouts/AppMain.vue')['default']
    Breadcrumb: typeof import('./components/common/Breadcrumb.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FolderManager: typeof import('./components/UserProfile/FolderManager.vue')['default']
    Hamburger: typeof import('./components/common/Hamburger.vue')['default']
    HighlightText: typeof import('./components/HighlightText.vue')['default']
    Link: typeof import('./components/layouts/Sidebar/Link.vue')['default']
    Logo: typeof import('./components/layouts/Sidebar/Logo.vue')['default']
    MessageNavigationControl: typeof import('./components/MessageNavigationControl.vue')['default']
    Navbar: typeof import('./components/layouts/Navbar.vue')['default']
    RightPanel: typeof import('./components/common/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./components/common/Screenfull.vue')['default']
    ScrollPane: typeof import('./components/layouts/TagsView/ScrollPane.vue')['default']
    Settings: typeof import('./components/layouts/Settings/index.vue')['default']
    Sidebar: typeof import('./components/layouts/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./components/layouts/Sidebar/SidebarItem.vue')['default']
    TagsView: typeof import('./components/layouts/TagsView/index.vue')['default']
    UserDetailDrawer: typeof import('./components/UserDetailDrawer.vue')['default']
  }
}
